const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //user
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',

    //admin
    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAIL: 'FETCH_GENDER_FAIL',

    FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',
    FETCH_POSITION_FAIL: 'FETCH_POSITION_FAIL',

    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAIL: 'FETCH_ROLE_FAIL',

    FETCH_REQUIRED_DOCTOR_INFO_SUCCESS: 'FETCH_REQUIRED_DOCTOR_INFO_SUCCESS',
    FETCH_REQUIRED_DOCTOR_INFO_FAIL: 'FETCH_REQUIRED_DOCTOR_INFO_FAIL',

    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAIL: 'CREATE_USER_FAIL',

    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAIL: 'EDIT_USER_FAIL',

    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAIL: 'DELETE_USER_FAIL',

    FETCH_ALL_USER_SUCCESS: 'FETCH_ALL_USER_SUCCESS',
    FETCH_ALL_USER_FAIL: 'FETCH_ALL_USER_FAIL',

    FETCH_TOP_DOCTOR_SUCCESS: 'FETCH_TOP_DOCTOR_SUCCESS',
    FETCH_TOP_DOCTOR_FAIL: 'FETCH_TOP_DOCTOR_FAIL',

    FETCH_ALL_DOCTOR_SUCCESS: 'FETCH_ALL_DOCTOR_SUCCESS',
    FETCH_ALL_DOCTOR_FAIL: 'FETCH_ALL_DOCTOR_FAIL',

    CREATE_DETAIL_DOCTOR_SUCCESS: 'CREATE_DETAIL_DOCTOR_SUCCESS',
    CREATE_DETAIL_DOCTOR_FAIL: 'CREATE_DETAIL_DOCTOR_FAIL',

    FETCH_ALLCODE_SCHEDULE_TIME_SUCCESS: 'FETCH_ALLCODE_SCHEDULE_TIME_SUCCESS',
    FETCH_ALLCODE_SCHEDULE_TIME_FAIL: 'FETCH_ALLCODE_SCHEDULE_TIME_FAIL',

    FETCH_ALL_SPECIALTY_SUCCESS: 'FETCH_ALL_SPECIALTY_SUCCESS',
    FETCH_ALL_SPECIALTY_FAIL: 'FETCH_ALL_SPECIALTY_FAIL',

    CREATE_SPECIALTY_SUCCESS: 'CREATE_SPECIALTY_SUCCESS',
    CREATE_SPECIALTY_FAIL: 'CREATE_SPECIALTY_FAIL',

    EDIT_SPECIALTY_SUCCESS: 'EDIT_SPECIALTY_SUCCESS',
    EDIT_SPECIALTY_FAIL: 'EDIT_SPECIALTY_FAIL',

    DELETE_SPECIALTY_SUCCESS: 'DELETE_SPECIALTY_SUCCESS',
    DELETE_SPECIALTY_FAIL: 'DELETE_SPECIALTY_FAIL',

    FETCH_ALL_CLINIC_SUCCESS: 'FETCH_ALL_CLINIC_SUCCESS',
    FETCH_ALL_CLINIC_FAIL: 'FETCH_ALL_CLINIC_FAIL',

    CREATE_CLINIC_SUCCESS: 'CREATE_CLINIC_SUCCESS',
    CREATE_CLINIC_FAIL: 'CREATE_CLINIC_FAIL',

    DELETE_CLINIC_SUCCESS: 'DELETE_CLINIC_SUCCESS',
    DELETE_CLINIC_FAIL: 'DELETE_CLINIC_FAIL',

    EDIT_CLINIC_SUCCESS: 'EDIT_CLINIC_SUCCESS',
    EDIT_CLINIC_FAIL: 'EDIT_CLINIC_FAIL',

    FETCH_ALL_HANDBOOK_SUCCESS: 'FETCH_ALL_HANDBOOK_SUCCESS',
    FETCH_ALL_HANDBOOK_FAIL: 'FETCH_ALL_HANDBOOK_FAIL',

    CREATE_HANDBOOK_SUCCESS: 'CREATE_HANDBOOK_SUCCESS',
    CREATE_HANDBOOK_FAIL: 'CREATE_HANDBOOK_FAIL',

    DELETE_HANDBOOK_SUCCESS: 'DELETE_HANDBOOK_SUCCESS',
    DELETE_HANDBOOK_FAIL: 'DELETE_HANDBOOK_FAIL',

    EDIT_HANDBOOK_SUCCESS: 'EDIT_HANDBOOK_SUCCESS',
    EDIT_HANDBOOK_FAIL: 'EDIT_HANDBOOK_FAIL',

    FETCH_ALL_SCHEDULE_DOCTOR_BY_DATE_SUCCESS: 'FETCH_ALL_SCHEDULE_DOCTOR_BY_DATE_SUCCESS',
    FETCH_ALL_SCHEDULE_DOCTOR_BY_DATE_FAIL: 'FETCH_ALL_SCHEDULE_DOCTOR_BY_DATE_FAIL',

    EDIT_SCHEDULE_SUCCESS: 'EDIT_SCHEDULE_SUCCESS',
    EDIT_SCHEDULE_FAIL: 'EDIT_SCHEDULE_FAIL',

    DELETE_SCHEDULE_SUCCESS: 'DELETE_SCHEDULE_SUCCESS',
    DELETE_SCHEDULE_FAIL: 'DELETE_SCHEDULE_FAIL',
})

export default actionTypes;